import type { FunctionalComponent } from 'vue'
import {
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Check,
  ChevronDown,
  CircleCheck,
  Clock,
  Coins,
  Copy,
  Droplets,
  ExternalLink,
  Globe,
  GraduationCap,
  Info,
  KeyRound,
  Landmark,
  LoaderCircle,
  LogOut,
  Menu,
  Monitor,
  Network,
  NotebookPen,
  Play,
  RefreshCw,
  Rocket,
  Server,
  ServerOff,
  ShieldCheck,
  Smartphone,
  TriangleAlert,
  Trophy,
  Wallet,
  X,
  Zap,
} from 'lucide-vue-next'

/*
 * Curated icon set — the only lucide icons bundled into the app.
 * Keys are kebab-case lucide names; add new icons here as tasks need them.
 */
export const iconMap: Record<string, FunctionalComponent> = {
  wallet: Wallet,
  'graduation-cap': GraduationCap,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'refresh-cw': RefreshCw,
  check: Check,
  info: Info,
  'triangle-alert': TriangleAlert,
  'circle-check': CircleCheck,
  'loader-circle': LoaderCircle,
  menu: Menu,
  x: X,
  copy: Copy,
  'log-out': LogOut,
  'chevron-down': ChevronDown,
  'external-link': ExternalLink,
  rocket: Rocket,
  trophy: Trophy,
  'book-open': BookOpen,
  coins: Coins,
  'notebook-pen': NotebookPen,
  network: Network,
  zap: Zap,
  'key-round': KeyRound,
  landmark: Landmark,
  play: Play,
  'shield-check': ShieldCheck,
  clock: Clock,
  server: Server,
  'server-off': ServerOff,
  monitor: Monitor,
  smartphone: Smartphone,
  globe: Globe,
  droplets: Droplets,
}
